### PR TITLE
chore(github): update codeowners

### PR DESCRIPTION
**Pull request by felixmr1**

### CODE REVIEW

**Comment by felixmr1** [comment]
@odsod are you admin on this repo? If so, could you update the new team in codeowners as moderator?

**Review by sousandrei — APPROVED** [review]

**Comment by sousandrei** [comment]
@felixmr1 make sure to change the repo ownership too :D

**Comment by felixmr1** [comment]
> @felixmr1 make sure to change the repo ownership too :D

Jup, hence my previous comment!

**Comment by Edholm** [comment]
not needed anymore :)

**Pull request closed without merging**
